# Generated by Django 2.0.5 on 2018-07-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historic_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=15)),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('amount', models.CharField(max_length=10)),
                ('rows', models.IntegerField()),
                ('file_name', models.CharField(max_length=50)),
                ('excel_file', models.FileField(upload_to='')),
                ('tab_delimited_file', models.FileField(upload_to='')),
            ],
        ),
    ]
