# Generated by Django 2.0.5 on 2018-07-02 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='non_profit_markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('markup_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='paper_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='print_price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('cost', models.DecimalField(decimal_places=5, max_digits=7)),
                ('cost_context', models.CharField(choices=[('per Square Inch', 'per Square Inch'), ('per Square Foot', 'per Square Foot')], default='per Square Inch', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('paper_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wide_format_pricing.paper_type')),
            ],
        ),
        migrations.CreateModel(
            name='profit_markup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('markup_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
