# Generated by Django 2.0.5 on 2018-07-02 18:58

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=60)),
                ('tag', models.CharField(choices=[('Webdesk', 'Webdesk'), ('Printing', 'Printing'), ('Mailing', 'Mailing'), ('Management', 'Management'), ('Administration', 'Administration'), ('Students', 'Students')], max_length=150)),
                ('theme_description', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=255)),
                ('topic_description', tinymce.models.HTMLField()),
                ('topic_theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repository.theme')),
            ],
        ),
    ]
