# Generated by Django 2.0.5 on 2018-07-01 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='managed_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_id', models.CharField(max_length=10)),
                ('stock_name', models.CharField(max_length=50)),
                ('threshold', models.IntegerField()),
                ('current_inventory', models.IntegerField(blank=True, default=0)),
                ('inventory_url', models.CharField(max_length=1000)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.department')),
            ],
        ),
    ]
