# Generated by Django 2.0.5 on 2018-07-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managed_stock',
            name='inventory_url',
        ),
        migrations.AlterField(
            model_name='managed_stock',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.department'),
        ),
    ]
